# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cicd_master CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check repo
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install package
      run: /home/CICD/actions-runner && npm i

    - name: install pm2
      run: /home/CICD/actions-runner && npm install pm2 -g

    - name: Re-check PM2
      run: /home/CICD/actions-runner && pm2 -v

    - name: cd to directory
      run: /home/CICD/actions-runner && git pull https://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@github.com/bearfixbug/cicd_starter.git

    - name: Restart PM2
      run: pm2 restart 2